# General CI workflow that exercises both backend and frontend, triggered
# for commits on master branch and PRs.
name: CI Pipeline [Continuous]

# Runs this workflow when:
# * a pull request is opened or reopened or when the head branch of the pull
#   request is updated
# * there's a push or pull request to the "master" branch of the repository.
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/reusable_ci.yml
