# 
name: CI Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  backend_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          echo "checkout backend"

  frontend_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          echo "checkout frontend"