name: Deploy

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}, image ${{ inputs.image }}

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Target environment'
        required: true
        type: choice
        options:
        - production
        - staging
      image:
        description: 'Image name'
        required: true
        type: string

jobs:

  ci:
    name: CI
    uses: ./.github/workflows/reusable_ci.yml
