name: Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target environment'
        required: true
        type: choice
        options:
        - production
        - staging

jobs:

  backend_build:
    name: Backend / Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          echo "checkout backend"