name: Release

run-name: Building image for ${{ inputs.hash }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      hash:
        description: 'SHA of the commit'
        required: true
        type: string

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/reusable_ci.yml