# Reusable workflow for CI pipeline that runs all the compilation, linter and
# tests.
name: Release [Continuous]

# Runs this workflow when:
# * a pull request is opened or reopened or when the head branch of the pull
#   request is updated
# * there's a push or pull request to the "master" branch of the repository.
on:
  release:
    types: [published]

jobs:
  ci:
    name: CI Pipeline
    uses: ./.github/workflows/reusable_ci.yml